name: Test Adder
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run unit tests
        run: python -m test_main

  deploy:
    needs: test
    runs-on: windows-latest
    if: ${{ always() }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          echo "Deploying the application..."
